version: "3.1"

services:
  php:
    build: docker/php
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  spec:
    image: phpspec/phpspec
    volumes:
      - ./app:/app

