version: "3.1"

services:
  php:
    build: docker/php
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  spec:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    working_dir: /app
#    entrypoint: vendor/bin/phpspec
    command: ls
#    volumes:
#      - ./app:/app

  unit:
    build: docker/php
    command: bin/phpunit
    volumes:
      - ./app:/app


